name: Deploy to Dev Environment (dev.yoneda.cc)

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Dev FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.DEV_FTP_SERVER }}
        username: ${{ secrets.DEV_FTP_USERNAME }}
        password: ${{ secrets.DEV_FTP_PASSWORD }}
        local-dir: ./current/build/
        server-dir: /yoneda.cc/public_html/dev.yoneda.cc/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/README.md 
